// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKiRepPgF5pBR0wkCNaAJfQEITjdLml8o',
    appId: '1:746798883016:android:1fc3715b645bbf4f50c5fd',
    messagingSenderId: '746798883016',
    projectId: 'ecommerce-app-234dd',
    databaseURL: 'https://ecommerce-app-234dd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerce-app-234dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiI1vQ0imXV_GGSJrhCqvtbTbUyPSBtTk',
    appId: '1:746798883016:ios:504908f7f9d1d7db50c5fd',
    messagingSenderId: '746798883016',
    projectId: 'ecommerce-app-234dd',
    databaseURL: 'https://ecommerce-app-234dd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerce-app-234dd.firebasestorage.app',
    iosBundleId: 'com.example.skillbridgeEcommerceProject',
  );
}
